services:
  wordsnap:
    image: kliszaj/wordsnap:latest
    container_name: wordsnap
    restart: unless-stopped
    user: "99:100"
    environment:
      DATA_DIR: /app/data
    ports:
      - "8090:8080"
    volumes:
      - /mnt/user/appdata/wordsnap/data:/app/data
